### ISSUE TITLE
Fails with AttributeError on install

### ISSUE THREAD

**Issue by thusoy** [ninjaaron/fast-entry_points#3]
Hi, thanks for writing this, great to see an attempt to do something about this problem!

I got an issue when trying to install on Travis:
```
running build_ext
Creating /home/travis/build/thusoy/remodep/venv/lib/python2.7/site-packages/remodep.egg-link (link to .)
Adding remodep 1.0.0 to easy-install.pth file
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/travis/build/thusoy/remodep/setup.py", line 50, in <module>
    'Programming Language :: Python :: 3.5',
  File "/usr/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/travis/build/thusoy/remodep/venv/local/lib/python2.7/site-packages/setuptools/command/develop.py", line 32, in run
    self.install_for_development()
  File "/home/travis/build/thusoy/remodep/venv/local/lib/python2.7/site-packages/setuptools/command/develop.py", line 132, in install_for_development
    self.process_distribution(None, self.dist, not self.no_deps)
  File "/home/travis/build/thusoy/remodep/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 680, in process_distribution
    self.install_egg_scripts(dist)
  File "/home/travis/build/thusoy/remodep/venv/local/lib/python2.7/site-packages/setuptools/command/develop.py", line 160, in install_egg_scripts
    self.install_wrapper_scripts(dist)
  File "/home/travis/build/thusoy/remodep/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 751, in install_wrapper_scripts
    for args in ScriptWriter.best().get_args(dist):
  File "fastentrypoints.py", line 29, in get_args
    cls._ensure_safe_name(name)
AttributeError: type object 'ScriptWriter' has no attribute '_ensure_safe_name'
```

The full output and attempted command is in [this repo](https://github.com/thusoy/remodep), it's very small and simple if you want to take a look if there's anything I've done wrong. It works with me locally, so I'm thinking it might be a pip/setuptools version issue? Have you tried running it on any CI yourself?

**Comment by ninjaaron** [comment]
Hi!
I haven't tried Travis myself. My suspicion is that your Travis machine has an older version of setuptools where the `ScriptWriter` class doesn't have the `_ensure_safe_name` method, but I have no way to confirm this. I inlined the method's contents from my version of setuptools. Hopefully this helps!

Just a note: This project really doesn't fix the problem with path enumeration in package_resources, it just steps around it for entry_points. If your software uses packages_resource somewhere else; e.g. by importing it directly or using a library like `requests`; fastentrypoints won't help! The maintainers for setuptools are presently very focused on the transition to `distlib`, which, while great, means this problem will probably never be fixed in setuptools, and we'll probably just have to wait for this major backend transition to go through before the issues is really solved.

**Comment by thusoy** [comment]
Hi! Yeah, I've read through the related issues around this, but for my use case right now this is perfect. Your fix is missing an `import re`, but with that I got green lights on all major python versions: https://travis-ci.org/thusoy/remodep/builds/203285559, thanks a bunch!

**Comment by ninjaaron** [comment]
Great! I forgot the `import re` at first, but it's in the next commit!
